from Arbol_Bin_Busq import *

if __name__ == '__main__':
    arbolB = Arbol_Binario_Busqueda()
    arbolB.Insertar(2)
    arbolB.Insertar(2)
    arbolB.Insertar(5)
    arbolB.Insertar(8)
    arbolB.Insertar(4)
    arbolB.Insertar(7)
    arbolB.Insertar(22)
    arbolB.Insertar(17)
    arbolB.Insertar(56)
    arbolB.Insertar(35)
    arbolB.Insertar(42)
    arbolB.Insertar(71)
    print("antes de suprimir")
    print("\n inorden")
    arbolB.In_Orden()
    print("\n preorden")
    arbolB.Pre_Orden()
    print("\n postorden")
    arbolB.Post_Orden()
    #suprimie
    arbolB.Suprimir(22)
    arbolB.Suprimir(7)
    arbolB.Suprimir(2)
    print("\n despues de suprimir")
    print("\n inorden")
    arbolB.In_Orden()
    print("\n preorden")
    arbolB.Pre_Orden()
    print("\n postorden")
    arbolB.Post_Orden()